name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      
      - name: Generate PlantUML diagrams
        uses: ./.github/actions/plantuml-action  # Reference the custom action in the same repo
        with:
          diagram_dir: docs/diagrams  # Specify the directory with .puml files
          output_dir: docs/diagrams/output  # Specify where to save the generated images

      - name: Upload artifacts for deployment
        uses: actions/upload-artifact@v3
        with:
          name: deployment-files
          path: docs

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          name: deployment-files



