name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main
      - patch-*
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write  # Explicitly give permission for OIDC token usage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # You can adjust the Ruby version here
          bundler-cache: true

      # Step 3: Install Dependencies
      - name: Install Jekyll and Bundler
        run: |
          bundle install

      - name: Create diagrams folder
        run: mkdir -p assets/diagrams

      - name: Generate PlantUML diagrams
        uses: ./.github/actions/plantuml-action  # Reference the custom action in the same repo
        with:
          diagram_dir: docs/diagrams  # Specify the directory with .puml files
          output_dir: assets/diagrams  # Specify where to save the generated images

			- name: Move assets if necessary
  			run: |
    			if [ -d "docs/diagrams/assets/diagrams" ]; then
      			mv docs/diagrams/assets/diagrams/* assets/diagrams/
    		fi

      # Step 4: Build Jekyll site
      - name: Build Jekyll Site
        run: bundle exec jekyll build

      # Step 5: Deploy to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write 
      id-token: write  # Explicitly give permission for OIDC token usage

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



